### ISSUE TITLE
Improve creating complex excels

### ISSUE THREAD

**Issue by SomayeEbrahimi** [farshaddavoudi/ExcelWizard#6]
Thanks for your great package, I used it in many projects and it works fine.

however, it is a bit hard to use in some cases:
- The Excel model is not only a complex object but also there are plenty of methods in the main Service which is confusing. 
- The Table model is built manually, but in many dynamic contexts. I think, if you create a binding model just like GridExcelLayout, it would be highly easier.

**Comment by farshaddavoudi** [comment]
Thanks for your comment @SomayeEbrahimi 

I agree with you and noticed this complexity in my projects too.  I will rewrite the project with Builder Design Pattern which I believe is the solution for creating Excel object complexity. Also about Table binding to a model I consider it in my work. 

Best regards

**Comment by farshaddavoudi** [comment]
This issue was closed by changing the main classes and using the Builder Pattern to create them. Now it is very straightforward to work with in action ;)
